# Generated by Django 4.2.7 on 2023-12-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petseeker',
            name='pref_location',
        ),
        migrations.AlterField(
            model_name='petseeker',
            name='pref_age',
            field=models.CharField(choices=[('none', 'none'), ('new', 'newborn'), ('young', 'young'), ('adult', 'adult'), ('senior', 'senior')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='petseeker',
            name='pref_personality',
            field=models.CharField(choices=[('none', 'no behaviour preference'), ('very active', 'very active'), ('active', 'active'), ('laid-back', 'laid-back'), ('lap', 'lap-pet')], default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='petseeker',
            name='pref_sex',
            field=models.CharField(choices=[('none', 'no gender preference'), ('F', 'female'), ('M', 'male')], default='none', max_length=5),
        ),
        migrations.AlterField(
            model_name='petseeker',
            name='pref_size',
            field=models.CharField(choices=[('none', 'no size preference'), ('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'extra large')], default='none', max_length=5),
        ),
    ]
