# Generated by Django 4.2.7 on 2023-12-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="petseeker",
            name="pref_age",
            field=models.CharField(
                choices=[
                    ("none", "none"),
                    ("new", "newborn"),
                    ("young", "young"),
                    ("adult", "adult"),
                    ("senior", "senior"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="petseeker",
            name="pref_animal",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="petseeker",
            name="pref_breed",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="petseeker",
            name="pref_colour",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="petseeker",
            name="pref_personality",
            field=models.CharField(
                choices=[
                    ("none", "no behaviour preference"),
                    ("very active", "very active"),
                    ("active", "active"),
                    ("laid-back", "laid-back"),
                    ("lap", "lap-pet"),
                ],
                default="none",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="petseeker",
            name="pref_sex",
            field=models.CharField(
                choices=[
                    ("none", "no gender preference"),
                    ("F", "female"),
                    ("M", "male"),
                ],
                default="none",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="petseeker",
            name="pref_size",
            field=models.CharField(
                choices=[
                    ("none", "no size preference"),
                    ("S", "small"),
                    ("M", "medium"),
                    ("L", "large"),
                    ("XL", "extra large"),
                ],
                default="none",
                max_length=5,
            ),
        ),
    ]
