# Generated by Django 4.2.7 on 2023-12-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(choices=[('comment', 'Someone has commented on your shelter.'), ('application', 'Someone has commented on your application.'), ('match', 'A new listing matches your preferences!')], max_length=13),
        ),
    ]
