# Generated by Django 5.0 on 2023-12-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='title',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
