# Generated by Django 4.2.7 on 2023-12-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blogcontent_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
