# Generated by Django 4.2.7 on 2023-11-11 23:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='health',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('N/A', 'N/A'), ('vaccinated', 'vaccinated'), ('spayed/neutered', 'spayed/neutered')], max_length=28),
        ),
    ]
