# Generated by Django 4.2.7 on 2023-11-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='method_of_payment',
        ),
        migrations.AlterField(
            model_name='application',
            name='above_twentyone',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='adopting_for',
            field=models.CharField(choices=[('myself', 'myself'), ('family', 'my family')], max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='children',
            field=models.CharField(choices=[('kids', 'kids'), ('none', 'no kids')], max_length=5),
        ),
        migrations.AlterField(
            model_name='application',
            name='current_pets',
            field=models.CharField(choices=[('none', 'no pet(s)'), ('cat', 'cat(s)'), ('dog', 'dog(s)'), ('both', 'dog(s) and cat(s)'), ('other', 'other pet(s)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='currently_insured',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='ideal_pet',
            field=models.CharField(choices=[('none', 'none'), ('new', 'newborn'), ('young', 'young'), ('adult', 'adult'), ('senior', 'senior')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='ideal_pet_behaviour',
            field=models.CharField(choices=[('none', 'no behaviour preference'), ('very active', 'very active'), ('active', 'active'), ('laid-back', 'laid-back'), ('lap', 'lap-pet')], default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='application',
            name='ideal_pet_sex',
            field=models.CharField(choices=[('none', 'no gender preference'), ('F', 'female'), ('M', 'male')], default='none', max_length=5),
        ),
        migrations.AlterField(
            model_name='application',
            name='ideal_pet_size',
            field=models.CharField(choices=[('none', 'no size preference'), ('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'extra large')], default='none', max_length=5),
        ),
        migrations.AlterField(
            model_name='application',
            name='insurance_name',
            field=models.CharField(choices=[('visa', 'Visa'), ('master', 'Mastercard'), ('amex', 'American Express'), ('interac', 'Interac E-transfer'), ('paypal', 'Paypal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='pet_owner_history',
            field=models.CharField(choices=[('previous', 'previous'), ('first', 'first-time')], max_length=10),
        ),
    ]
