# Generated by Django 4.2.7 on 2023-12-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='adopting_for',
            field=models.CharField(choices=[('myself', 'myself'), ('family', 'my family')], default='myself', max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='children',
            field=models.CharField(choices=[('kids', 'kids'), ('none', 'no kids')], default='none', max_length=5),
        ),
        migrations.AddField(
            model_name='application',
            name='current_pets',
            field=models.CharField(choices=[('none', 'no pet(s)'), ('cat', 'cat(s)'), ('dog', 'dog(s)'), ('both', 'dog(s) and cat(s)'), ('other', 'other pet(s)')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='pet_owner_history',
            field=models.CharField(choices=[('previous', 'previous'), ('first', 'first-time')], default='first', max_length=10),
        ),
    ]
