# Generated by Django 4.2.7 on 2023-12-03 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='adopting_for',
        ),
        migrations.RemoveField(
            model_name='application',
            name='children',
        ),
        migrations.RemoveField(
            model_name='application',
            name='pet_owner_history',
        ),
    ]
