# Generated by Django 4.2.7 on 2023-12-03 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_application_adopting_for_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='ideal_pet',
            new_name='ideal_pet_age',
        ),
        migrations.RemoveField(
            model_name='application',
            name='current_pets',
        ),
    ]
