# Generated by Django 4.2.7 on 2023-12-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='health',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='training',
        ),
        migrations.AlterField(
            model_name='listing',
            name='age',
            field=models.CharField(choices=[('new', 'newborn'), ('young', 'young'), ('adult', 'adult'), ('senior', 'senior')], max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='personality',
            field=models.CharField(choices=[('very active', 'very active'), ('active', 'active'), ('laid-back', 'laid-back'), ('lap', 'lap-pet')], max_length=15),
        ),
        migrations.AlterField(
            model_name='listing',
            name='size',
            field=models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'extra large')], max_length=5),
        ),
    ]
