# Generated by Django 4.2.7 on 2023-12-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_health_remove_listing_training_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='good_without',
        ),
    ]
