# Generated by Django 4.2.7 on 2023-12-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='accounttype',
            field=models.CharField(choices=[('petseeker', 'Pet Seeker'), ('petshelter', 'Pet Shelter')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
