# Generated by Django 4.2.7 on 2023-11-15 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("denied", "Denied"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("applicant_first_name", models.CharField(max_length=50)),
                ("applicant_last_name", models.CharField(max_length=50)),
                ("applicant_email", models.CharField(max_length=50)),
                ("applicant_phone_number", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("postal_code", models.CharField(max_length=6)),
                ("above_twentyone", models.CharField(max_length=50)),
                ("adopting_for", models.CharField(max_length=50)),
                ("children", models.CharField(max_length=50)),
                ("pet_owner_history", models.CharField(max_length=50)),
                ("current_pets", models.CharField(max_length=50)),
                ("ideal_pet", models.CharField(max_length=50)),
                ("ideal_pet_sex", models.CharField(max_length=50)),
                ("ideal_pet_size", models.CharField(max_length=50)),
                ("ideal_pet_behaviour", models.CharField(max_length=50)),
                ("currently_insured", models.CharField(max_length=50)),
                ("insurance_name", models.CharField(max_length=50)),
                ("method_of_payment", models.CharField(max_length=50)),
                (
                    "pet_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.listing",
                    ),
                ),
                (
                    "pet_seeker_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pet_seeker_applicant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-last_updated_at"],
            },
        ),
    ]
