# Generated by Django 4.2.7 on 2023-11-15 04:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applicationsp2", "0002_alter_application_belongs_to_shelter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="email",
            new_name="applicant_email",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="first_name",
            new_name="applicant_first_name",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="last_name",
            new_name="applicant_last_name",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="phone_number",
            new_name="applicant_phone_number",
        ),
        migrations.RemoveField(
            model_name="application",
            name="age",
        ),
        migrations.RemoveField(
            model_name="application",
            name="belongs_to_shelter",
        ),
        migrations.RemoveField(
            model_name="application",
            name="breed",
        ),
        migrations.RemoveField(
            model_name="application",
            name="sex",
        ),
        migrations.RemoveField(
            model_name="application",
            name="shelter_user",
        ),
        migrations.RemoveField(
            model_name="application",
            name="size",
        ),
    ]
