# Generated by Django 4.2.7 on 2023-11-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applicationsp2", "0003_rename_email_application_applicant_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("denied", "Denied"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
