# Generated by Django 4.2.7 on 2023-11-15 05:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applicationsp2", "0004_alter_application_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="status",
            new_name="application_status",
        ),
    ]
